### ISSUE TITLE
Change "Terminate" button to "Stop" in ACCORD portal.

### ISSUE THREAD

**Issue by nmagee** [uvarc/accord#18]
I think "Terminate" suggests getting rid of it for good. "Stop" might indicate they will be able to restart it again in the future.

<img width="700" alt="Screen Shot 2021-10-07 at 10 19 28 AM" src="https://user-images.githubusercontent.com/699798/136403564-d7589787-e8a5-4f3e-bb4b-3dbe33390a47.png">

**Comment by rkc7h** [comment]
@nmagee Changed and deployed to prod as requested
