### ISSUE TITLE
Jupyter launcher errors

### ISSUE THREAD

**Issue by mc2zk** [uvarc/accord#3]
When clicking on Notebook, Text file, Markdown, I get a `Permission denied` error message, because `Cannot read property 'path' of undefined`.  Does not matter which project group I launch Jupyter from.  Happens for both `uvarc` and `vogons`

**Comment by nmagee** [comment]
@mc2zk thank you for this. If you were to click on a main folder in the lefthand filenav bar (`project`, `scratch`,`home`), select that, and then create a text file or .md file, does that work successfully?

**Comment by rkc7h** [comment]
@nmagee All the PATH issues are fixed at this time hence closing this issue as well
