### ISSUE TITLE
Python-theia: Default dir for creating new files

### ISSUE THREAD

**Issue by ksiller** [uvarc/accord#5]
It seems that python-theia creates new files in the current directory.  When started, the current dir is /home but new files created in /home are not visible (or creation was skipped without error messages).  So a user has to change the current dir via explorer or--if /home is still the current dir--specify a relative path "user/file.py" as filename to create the file.  This may be a config item rather than a bug.  Maybe setting the startup dir to be /home/user instead of /home is more straightforward.

**Comment by rkc7h** [comment]
@ksiller this issue was resolved recently with some home path changes hence closing it. Please verify otherwise
