### ISSUE TITLE
Able to install numpy but not import

### ISSUE THREAD

**Issue by rsdmse** [uvarc/accord#6]
In JupyterLab, `!pip3 install numpy` succeeds (suggestion: create pip -> pip3 symlink) but in the next cell when I try to import it:

```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-9-0aa0b027fcb6> in <module>
----> 1 import numpy as np

ModuleNotFoundError: No module named 'numpy'
```

**Comment by rsdmse** [comment]
This fixed the problem:
`!echo "export PYTHONPATH=~/.local/lib/python3.6/site-packages" >> .bashrc`
The `.local` directory is automatically detected on Rivanna so that users don't need to add it to their PYTHONPATH.

**Comment by rkc7h** [comment]
@rsdmse this issue should have been resolved at this time hence closing it. Please verify if not otherwise.
