### ISSUE TITLE
Logout button doesn't fully log user out

### ISSUE THREAD

**Issue by cagancayco** [uvarc/accord#7]
After clicking the logout button, the user appears to be temporarily logged out but then is logged in again.

**Comment by nmagee** [comment]
@rkc7h could you find a workaround for this? We might simply need to close the tab of the user -- b/c I get the same behavior.

**Comment by rkc7h** [comment]
Currently the logout means refresh as there no true logout as the incommons/COmanage sessions last long. I will try attempting to close the window on logout or redirect to a logout page.

**Comment by rkc7h** [comment]
This issue is fixed the form logs out and now expects user to explicitly login.

**Comment by rkc7h** [comment]
@cagancayco can you please review and close this issue when you can.
