### ISSUE TITLE
No response when terminating session

### ISSUE THREAD

**Issue by cagancayco** [uvarc/accord#8]
When clicking the "Terminate" button, there is no indication that the termination process has begun for session. It is only apparent once the termination is complete and the session is no longer listed in "Current Sessions".

**Comment by nmagee** [comment]
I believe @rkc7h has modified this behavior. If you have a moment could you please check again?

https://accord-dev.uvarc.io/ is the current DEV cluster, with COmanage authentication.

**Comment by rkc7h** [comment]
@nmagee yes this should be closed. I will assign it to @cagancayco to verify the same and close.

**Comment by rkc7h** [comment]
@cagancayco can you please try at https://accord-dev.uvarc.io, test and close it out
